parameters:
  name: null
  pool: {}
  matrix: {}
  dockerClientOS: null
  useRemoteDockerServer: false
jobs:
- job: ${{ parameters.name }}
  condition: "
    and(
      succeeded(),
      ${{ parameters.matrix }},
      or(
        eq(variables['singlePhase'], ''),
        eq(variables['singlePhase'], 'build')))"
  dependsOn: GenerateMatrices
  pool: ${{ parameters.pool }}
  strategy:
    matrix: $[ ${{ parameters.matrix }} ]
  variables:
    osVersion: ${{ parameters.osVersion }}
    ${{ if eq(variables['isPullRequestBuild'], 'false') }}:
      registryPushParameters: --registry-override $(acr.server)
        --repo-prefix $(stagingRepoPrefix)
        --push
        --username $(acr.userName)
        --password $(BotAccount-dotnet-docker-acr-bot-password)
    ${{ if eq(variables['isPullRequestBuild'], 'true') }}:
      registryPushParameters: ""
  steps:
  - template: ${{ format('../steps/init-docker-{0}.yml', parameters.dockerClientOS) }}
    parameters:
      setupRemoteDockerServer: ${{ parameters.useRemoteDockerServer }}
  - script: >
      $(runImageBuilderCmd) build
      --manifest $(manifest)
      $(imageBuilderPaths)
      --os-type $(osType)
      --os-version "$(osVersion)"
      --architecture $(architecture)
      --retry
      $(registryPushParameters)
      $(imageBuilder.queueArgs)
    displayName: Build Images
  - ${{ if eq(variables['isPullRequestBuild'], 'true') }}:
    - template: ${{ format('../steps/test-images-{0}-client.yml', parameters.dockerClientOS) }}
      parameters:
        cleanupDocker: false
  - template: ${{ format('../steps/cleanup-docker-{0}.yml', parameters.dockerClientOS) }}
    parameters:
      cleanupRemoteDockerServer: ${{ parameters.useRemoteDockerServer }}
